spring.application.name=GermanCollege
server.port=8085
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7


spring.datasource.url=jdbc:mysql://localhost:3306/german_college_ai
spring.datasource.username=root
spring.datasource.password=Chirag@2408

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Logging
logging.level.com.example.GermanCollege=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG

# Scraper Settings
scraper.hochschulkompass.search-url=https://www.hochschulkompass.de/en/study/search.html
scraper.daad.page-size=20
scraper.delay-between-requests=1000